services:
  desha-moulin:
    build: .
    container_name: desha-moulin
    ports:
      - "8086:80"
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true